<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';

const auth = useAuthStore();
const router = useRouter();

const newPassword = ref('');
const confirmPassword = ref('');
const error = ref('');
const loading = ref(false);

async function submit() {
  if (newPassword.value !== confirmPassword.value) {
    error.value = 'Passwords do not match';
    return;
  }
  if (newPassword.value.length < 8) {
    error.value = 'Password must be at least 8 characters';
    return;
  }

  error.value = '';
  loading.value = true;
  try {
    const r = await fetch(`/api/users/${auth.user?.id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        ...auth.authHeaders()
      },
      body: JSON.stringify({ password: newPassword.value }),
    });
    if (!r.ok) {
      const msg = await r.text();
      throw new Error(msg || 'Failed to update password');
    }
    await auth.validateSession();
    router.push('/');
  } catch (e: any) {
    error.value = e.message || 'Update failed';
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center relative overflow-hidden bg-slate-950">
    <div class="absolute inset-0 overflow-hidden pointer-events-none">
      <div class="absolute top-[10%] left-[15%] w-[400px] h-[400px] rounded-full bg-cyan-500/[0.04] blur-[100px]"></div>
      <div class="absolute bottom-[10%] right-[15%] w-[350px] h-[350px] rounded-full bg-violet-500/[0.04] blur-[100px]"></div>
    </div>
    <div class="absolute inset-0 opacity-[0.03]" style="background-image: radial-gradient(circle, #fff 1px, transparent 1px); background-size: 32px 32px;"></div>

    <div class="relative z-10 w-full max-w-sm px-4">
      <div class="text-center mb-8 animate-fade-up">
        <h1 class="font-display text-2xl font-extrabold tracking-[0.12em] text-white mb-2">SECURITY</h1>
        <p class="text-sm text-slate-500">Change your password</p>
      </div>

      <div class="glass p-7 space-y-5 animate-fade-up delay-100">
        <div class="text-sm text-slate-400 text-center">
          For security reasons, you must change your autogenerated password before continuing.
        </div>

        <div>
          <label class="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2 block">New Password</label>
          <input v-model="newPassword" type="password" placeholder="Min 8 characters" @keyup.enter="submit" class="input-glass" />
        </div>

        <div>
          <label class="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2 block">Confirm Password</label>
          <input v-model="confirmPassword" type="password" @keyup.enter="submit" class="input-glass" />
        </div>

        <div v-if="error" class="flex items-center gap-2 px-4 py-3 rounded-xl text-xs bg-rose-500/10 border border-rose-500/20 text-rose-400">
          <span class="mdi mdi-alert-circle"></span>
          {{ error }}
        </div>

        <button
          @click="submit"
          :disabled="loading || !newPassword || !confirmPassword"
          class="w-full btn-gradient justify-center py-2.5"
        >
          <span v-if="loading" class="mdi mdi-loading animate-spin"></span>
          {{ loading ? 'Updating…' : 'Update Password' }}
        </button>
      </div>
    </div>
  </div>
</template>
