<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';

const auth   = useAuthStore();
const router = useRouter();

const newPassword     = ref('');
const confirmPassword = ref('');
const error           = ref('');
const loading         = ref(false);

async function submit() {
  if (newPassword.value !== confirmPassword.value) {
    error.value = 'Passwords do not match';
    return;
  }
  if (newPassword.value.length < 8) {
    error.value = 'Password must be at least 8 characters';
    return;
  }

  error.value   = '';
  loading.value = true;
  try {
    const r = await fetch(`/api/users/${auth.user?.id}`, {
      method: 'PUT',
      headers: { 
        'Content-Type': 'application/json',
        ...auth.authHeaders()
      },
      body: JSON.stringify({ password: newPassword.value }),
    });
    
    if (!r.ok) {
      const msg = await r.text();
      throw new Error(msg || 'Failed to update password');
    }

    // Refresh session to clear the flag
    await auth.validateSession();
    router.push('/');
  } catch (e: any) {
    error.value = e.message || 'Update failed';
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="login-bg min-h-screen flex items-center justify-center p-4">
    <div class="login-orb login-orb-1"></div>
    <div class="login-orb login-orb-2"></div>

    <div class="w-full max-w-sm relative z-10 anim-slide-up">
      <div class="text-center mb-10">
        <h1 class="login-brand">SECURITY</h1>
        <p class="login-tagline">Change your password</p>
      </div>

      <div class="login-card">
        <div class="mb-6 text-sm text-center" style="color: var(--text-muted);">
          For security reasons, you must change your autogenerated password before continuing.
        </div>

        <div class="space-y-4">
          <div>
            <label class="block section-label mb-2">New Password</label>
            <input
              v-model="newPassword"
              type="password"
              placeholder="Min 8 characters"
              @keyup.enter="submit"
              class="field"
            />
          </div>

          <div>
            <label class="block section-label mb-2">Confirm Password</label>
            <input
              v-model="confirmPassword"
              type="password"
              @keyup.enter="submit"
              class="field"
            />
          </div>

          <div v-if="error" class="flex items-center gap-2 px-3 py-2.5 rounded-xl text-xs" style="background: var(--red-dim); color: var(--red); border: 1px solid var(--red-border);">
            <span class="mdi mdi-alert-circle shrink-0"></span>
            {{ error }}
          </div>

          <button
            @click="submit"
            :disabled="loading || !newPassword || !confirmPassword"
            class="btn-primary w-full justify-center py-2.5 mt-1"
          >
            <span v-if="loading" class="mdi mdi-loading spin"></span>
            {{ loading ? 'Updating…' : 'Update Password' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.login-bg {
  background: var(--bg-base);
  overflow: hidden;
  position: relative;
}

.login-bg::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image: radial-gradient(circle, rgba(148, 163, 184, 0.04) 1px, transparent 1px);
  background-size: 28px 28px;
  pointer-events: none;
}

.login-orb {
  position: absolute;
  border-radius: 50%;
  filter: blur(80px);
  pointer-events: none;
}
.login-orb-1 {
  width: 360px; height: 360px;
  background: radial-gradient(circle, rgba(56, 189, 248, 0.07) 0%, transparent 70%);
  top: -80px; left: -80px;
}
.login-orb-2 {
  width: 280px; height: 280px;
  background: radial-gradient(circle, rgba(14, 165, 233, 0.05) 0%, transparent 70%);
  bottom: -60px; right: -60px;
}

.login-brand {
  font-family: var(--font-display);
  font-size: 26px; font-weight: 800;
  letter-spacing: 0.22em; color: var(--text-primary);
  margin-bottom: 6px;
}

.login-tagline {
  font-size: 11px; letter-spacing: 0.1em;
  text-transform: uppercase; color: var(--text-muted);
}

.login-card {
  background: var(--bg-elevated);
  border: 1px solid var(--border-mid);
  border-radius: 16px; padding: 28px;
  box-shadow: 0 24px 60px rgba(0, 0, 0, 0.5);
}
</style>
