//! Vorbis audio codec — decoder only (pure Rust via `lewton`).
//!
//! ## Wire header format for Vorbis
//!
//! The `header_data` blob in the `CodecHeader` message contains three
//! length-prefixed Vorbis setup packets (identification, comment, setup):
//!
//! ```text
//! u32  ident_len
//! u8[] ident_packet
//! u32  comment_len
//! u8[] comment_packet
//! u32  setup_len
//! u8[] setup_packet
//! ```
//!
//! Vorbis *encoding* is not supported; the server should use Opus or FLAC.
//! The decoder exists so that a Sonium client can connect to a Snapcast server
//! that is streaming Vorbis audio.

use lewton::audio::{read_audio_packet, PreviousWindowRight};
use lewton::header::{
    read_header_comment, read_header_ident, read_header_setup, IdentHeader, SetupHeader,
};

use sonium_common::{error::Result, SampleFormat, SoniumError};
use sonium_protocol::wire::{WireRead, WireWrite};

use crate::traits::Decoder;

// ── Decoder ───────────────────────────────────────────────────────────────────

pub struct VorbisDecoder {
    ident: IdentHeader,
    setup: SetupHeader,
    prev_window: PreviousWindowRight,
    fmt: SampleFormat,
}

impl VorbisDecoder {
    /// Construct from the `header_data` blob received in a `CodecHeader` message.
    pub fn from_header(data: &[u8]) -> Result<Self> {
        let mut r = WireRead::new(data);
        let ident_pkt = r.read_blob()?;
        let comment_pkt = r.read_blob()?;
        let setup_pkt = r.read_blob()?;

        let ident = read_header_ident(&ident_pkt)
            .map_err(|e| SoniumError::Codec(format!("vorbis ident header: {e}")))?;
        let _comment = read_header_comment(&comment_pkt)
            .map_err(|e| SoniumError::Codec(format!("vorbis comment header: {e}")))?;
        let setup = read_header_setup(
            &setup_pkt,
            ident.audio_channels,
            (ident.blocksize_0, ident.blocksize_1),
        )
        .map_err(|e| SoniumError::Codec(format!("vorbis setup header: {e}")))?;

        let fmt = SampleFormat::new(ident.audio_sample_rate, 16, ident.audio_channels as u16);

        Ok(Self {
            ident,
            setup,
            prev_window: PreviousWindowRight::new(),
            fmt,
        })
    }
}

impl Decoder for VorbisDecoder {
    fn decode(&mut self, input: &[u8], output: &mut Vec<i16>) -> Result<()> {
        // read_audio_packet returns Vec<Vec<i16>> — channels × samples.
        let decoded = read_audio_packet(&self.ident, &self.setup, input, &mut self.prev_window)
            .map_err(|e| SoniumError::Codec(format!("vorbis decode: {e}")))?;

        let n_ch = decoded.len();
        let n_samples = decoded.first().map(|c| c.len()).unwrap_or(0);

        // Interleave channels: [L0, R0, L1, R1, ...]
        output.reserve(n_samples * n_ch);
        for i in 0..n_samples {
            for ch in &decoded {
                output.push(ch[i]);
            }
        }
        Ok(())
    }

    fn sample_format(&self) -> SampleFormat {
        self.fmt
    }
}

// ── Header builder (server side, for round-trip) ──────────────────────────────

/// Build the `header_data` blob for a Vorbis `CodecHeader` message.
///
/// `ident`, `comment` and `setup` are the raw Vorbis header packets (as
/// received from the source or generated by an encoder).
pub fn vorbis_codec_header(ident: &[u8], comment: &[u8], setup: &[u8]) -> Vec<u8> {
    let mut w = WireWrite::with_capacity(12 + ident.len() + comment.len() + setup.len());
    w.write_blob(ident);
    w.write_blob(comment);
    w.write_blob(setup);
    w.finish()
}
